#!/usr/bin/env python

import ROOT
import sys 
import os

_ROOT_EXTENSION = ".root"

def check_path(path):
    if not os.path.exists(path):
        raise IOError("{} doesn't exist".format(path))

    if not os.path.isfile(path):
        raise IOError("{} is a directory.".format(path))

    extension = os.path.splitext(path)[-1]
    if not (extension == _ROOT_EXTENSION):
        raise IOError("{} is not ROOT file.".format(path))


def main():
    in_path = str(sys.argv[1])

    check_path(in_path)

    root_file = ROOT.TFile.Open(in_path, "READ")
    browser = ROOT.TBrowser()

    try:
        while True:
            continue
    except KeyboardInterrupt:
        root_file.Close()
        return None

if __name__ == "__main__":
    main()
